#!/usr/bin/env python3
"""
Personal AI Employee - Main Orchestrator

Manages the flow: External Input → Watcher → Needs_Action → Claude → Plan → Approval → MCP → Done → Logs
"""

import os
import json
import time
import threading
from pathlib import Path
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import subprocess
import sys


class ActionHandler(FileSystemEventHandler):
    """Handles new action files dropped into the Needs_Action folder"""

    def __init__(self, vault_path, logs_path):
        self.vault_path = Path(vault_path)
        self.logs_path = Path(logs_path)

    def on_created(self, event):
        if event.is_directory:
            return

        # Only process markdown files
        if event.src_path.endswith('.md'):
            print(f"New action file detected: {event.src_path}")
            self.process_action_file(event.src_path)

    def process_action_file(self, file_path):
        """Process a new action file by sending it to Claude for analysis"""
        try:
            # Log the detection
            self.log_activity("action_detected", {"file": file_path})

            # Move file to processing queue or send to Claude
            self.send_to_claude(file_path)

        except Exception as e:
            print(f"Error processing action file: {str(e)}")
            self.log_activity("error", {"file": file_path, "error": str(e)})

    def send_to_claude(self, file_path):
        """Send the action file to Claude for plan generation"""
        # This would integrate with Claude Code
        print(f"Sending {file_path} to Claude for analysis...")

        # For now, simulate Claude processing
        plan_content = self.simulate_claude_analysis(file_path)

        # Create a plan file in the appropriate location
        plan_file = self.create_plan_file(file_path, plan_content)

        # Log the plan generation
        self.log_activity("plan_generated", {"input_file": file_path, "output_plan": str(plan_file)})

        print(f"Plan generated: {plan_file}")

    def simulate_claude_analysis(self, file_path):
        """Simulate Claude's analysis and plan generation"""
        with open(file_path, 'r') as f:
            content = f.read()

        # In a real implementation, this would call Claude Code API
        # For now, create a simple plan based on the content
        plan = f"""# Action Plan Generated by Claude

Based on the input file: {os.path.basename(file_path)}

## Original Request:
{content}

---

## Proposed Actions:
1. Analyze the request in detail
2. Determine appropriate next steps
3. Execute approved actions
4. Log all activities

---

## Approval Status:
PENDING

---

## Execution Status:
NOT_STARTED

Generated at: {datetime.now().isoformat()}
"""
        return plan

    def create_plan_file(self, original_file_path, plan_content):
        """Create a plan file in the appropriate location"""
        original_filename = Path(original_file_path).stem
        plan_filename = f"{original_filename}_plan.md"
        plan_path = self.vault_path / "Daily" / plan_filename

        with open(plan_path, 'w') as f:
            f.write(plan_content)

        return plan_path

    def log_activity(self, activity_type, details):
        """Log activities to the Logs directory"""
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "activity_type": activity_type,
            "details": details
        }

        log_file = self.logs_path / f"activity_{datetime.now().strftime('%Y%m%d')}.jsonl"

        with open(log_file, 'a') as f:
            f.write(json.dumps(log_entry) + '\n')


class PlanExecutionHandler(FileSystemEventHandler):
    """Handles plan execution when approval is detected"""

    def __init__(self, vault_path, logs_path, needs_action_path):
        self.vault_path = Path(vault_path)
        self.logs_path = Path(logs_path)
        self.needs_action_path = Path(needs_action_path)

        # Guard set to track executed plans
        self.executed_plans = set()

    def on_modified(self, event):
        if event.is_directory:
            return

        # Only process markdown files that are plan files
        if event.src_path.endswith('_plan.md'):
             # Check if this plan was already executed
            if event.src_path in self.executed_plans:
             return  # Skip duplicate execution

            print(f"Plan file modified: {event.src_path}")
            self.check_and_execute_plan_if_approved(event.src_path)

    def check_and_execute_plan_if_approved(self, plan_path):
        """Check if plan has been approved and execute if appropriate"""

        try:
            if not os.path.exists(plan_path):
                return
            with open(plan_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Check if the plan is approved
            if "## Approval Status:\nAPPROVED" in content:
                print(f"Approved plan detected: {plan_path}")

                # Move the original file from Needs_Action to Approved folder if it exists
                original_filename = Path(plan_path).stem.replace('_plan', '')
                original_file_path = self.needs_action_path / f"{original_filename}.md"

                if original_file_path.exists():
                    approved_dir = self.vault_path.parent / "Approved"  # Go up one level to get to Approved
                    approved_dir.mkdir(exist_ok=True)

                    approved_file_path = approved_dir / original_file_path.name
                    original_file_path.rename(approved_file_path)
                    print(f"Moved original file to Approved: {approved_file_path}")

                # Execute the plan if it hasn't been started yet
                if "## Execution Status:\nNOT_STARTED" in content:
                    self.execute_plan(plan_path)

        except FileNotFoundError:
            # File may have been moved to Done folder — ignore safely
            return

        except Exception as e:
            print(f"Error checking plan approval: {str(e)}")
            self.log_activity("error", {"file": plan_path, "error": str(e)})

    def execute_plan(self, plan_path):
        """Execute a plan that has been approved"""
        plan_name = Path(plan_path).name

        # Update execution status to IN_PROGRESS
        with open(plan_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Replace Execution Status: NOT_STARTED with IN_PROGRESS
        updated_content = content.replace("## Execution Status:\nNOT_STARTED", "## Execution Status:\nIN_PROGRESS")

        with open(plan_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)

        # Log execution start
        self.log_activity("execution_started", {"file": plan_name})

        # Simulate 3 execution steps
        steps = [
            "Parsing plan",
            "Running simulated task",
            "Finalizing"
        ]

        for i, step in enumerate(steps):
            print(f"Step {i+1}/3: {step}")
            time.sleep(1)  # Sleep 1 second

            # Write log entry for each step
            self.log_activity("execution_step", {
                "file": plan_name,
                "step": step,
                "step_number": i+1
            })

        # Replace Execution Status: IN_PROGRESS with COMPLETED
        updated_content = content.replace("## Execution Status:\nIN_PROGRESS", "## Execution Status:\nCOMPLETED")

        # Move file to Done/ directory first
        done_dir = self.vault_path / "Done"
        done_dir.mkdir(exist_ok=True)

        destination_path = done_dir / Path(plan_path).name

        # Update the content in memory, then write to the new location
        with open(destination_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)

        # Remove the original file (in case the rename didn't happen implicitly)
        if Path(plan_path).exists():
            Path(plan_path).unlink()
        
        # Mark as executed to prevent duplicate execution
        self.executed_plans.add(plan_path)

        # Log execution completion
        self.log_activity("execution_completed", {"file": plan_name})

        print(f"Plan execution completed: {destination_path}")

    def log_activity(self, activity_type, details):
        """Log activities to the Logs directory"""
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "activity_type": activity_type,
            "details": details
        }

        log_file = self.logs_path / f"activity_{datetime.now().strftime('%Y%m%d')}.jsonl"

        with open(log_file, 'a') as f:
            f.write(json.dumps(log_entry) + '\n')


def main(stop_event=None):
    """Main entry point for the orchestrator"""
    # Define paths
    base_path = Path(__file__).parent
    needs_action_path = base_path / "Needs_Action"
    vault_path = base_path / "Vault"
    logs_path = base_path / "Logs"

    # Create Done directory if it doesn't exist
    done_dir = vault_path / "Done"
    done_dir.mkdir(exist_ok=True)

    # Create handlers
    action_handler = ActionHandler(vault_path, logs_path)
    plan_execution_handler = PlanExecutionHandler(vault_path, logs_path, needs_action_path)

    # Set up observers
    action_observer = Observer()
    action_observer.schedule(action_handler, str(needs_action_path), recursive=False)

    daily_path = vault_path / "Daily"
    daily_path.mkdir(exist_ok=True)  # Ensure Daily directory exists

    plan_observer = Observer()
    plan_observer.schedule(plan_execution_handler, str(daily_path), recursive=False)

    print(f"Starting AI Employee orchestrator...")
    print(f"Monitoring: {needs_action_path}")
    print(f"Monitoring: {daily_path}")
    print(f"Vault: {vault_path}")
    print(f"Logs: {logs_path}")

    # Start the observers
    action_observer.start()
    plan_observer.start()

    try:
        print("Orchestrator running. Press Ctrl+C to stop.")
        while not (stop_event and stop_event.is_set()):
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nShutting down orchestrator...")

    action_observer.stop()
    plan_observer.stop()

    action_observer.join(timeout=2)
    plan_observer.join(timeout=2)


if __name__ == "__main__":
    main()